// react-app/src/pages/List/index.js
import React,{useState, useEffect} from 'react';
import { Container, Navbar, Card, Form, Col} from "react-bootstrap";
import ModalCadastro from "../../components/ModalCadastro"
import ModalAtualizar from "../../components/ModalAtualizar"
import ModalExcluir from "../../components/ModalExcluir"

import "./style.css";

import { firebase } from '@firebase/app'
import "firebase/auth";
import firebasee from "../../firebase";

const db = firebasee.ref("/tarefas");

export default function List({history }) {

    const [listTarefas, setListTarefas] = useState([]);

    const getTarefas = async() =>  {

        var user = firebase.auth().currentUser;

        if(user){
        
        let listTarefas = [];

         const results = await db.get();
         
         results.forEach(result => {
             let key =  result.key;
             let data = result.val();;
             listTarefas.push({
                 key: key,
                 title: data.title,
                 description: data.description,
                 date: data.date,
                 time: data.time,
             });
         });
         return setListTarefas(listTarefas); 
        }
        console.log("sem usuario");
     }         
    
    useEffect(() => {
        
      getTarefas();
    // eslint-disable-next-line
    }, [listTarefas])


    const sair = () => {
        firebase.auth().signOut().then(() => {
            history.push(`/`);

            // Sign-out successful.
          }).catch((error) => {
            // An error happened.
          });
    }

    return (

        <Container fluid="as" className="Main">
            <div className="sairLogin" onClick={() => sair()}>Sair</div>
            <div className="boxTop">
                <div className="TituloEmpresa">Sistema de controle de atividades</div>
               

                <Navbar className="Navigation justify-content-between" >
                    <Navbar.Brand className="descricaoEmpresa"> Atividades cadastradas </Navbar.Brand>
                    <Form inline>
                       {/* <FormControl type="text" placeholder="Pesquisar" className=" mr-sm-2" /> */}
                        <ModalCadastro/>
                    </Form>
                </Navbar>
            </div>

            <div className="boxContainer">

            {listTarefas &&
              listTarefas.map((atividade, index) => (
                <Card style={{ width: '20rem', border: 'none', marginBottom: '10px' }} key={index}>
                    <Card.Body style={{ padding: '1.5rem' }}>
                        <Card.Title className="bodyTitle">{atividade.title}</Card.Title>
                        <Card.Text className="FormTitle">
                          {atividade.description}
                        </Card.Text>
                        <Card.Text>
                           <div className="FormDateTime">
                               <div>
                                     <i class="far fa-calendar"></i> {atividade.date}
                               </div>
                                <div>
                                    <i class="far fa-clock"></i> {atividade.time}
                                </div>
                           </div>
                        </Card.Text>
                        <Col xs={5} className="GroupBotaoStructure" >
                             <ModalAtualizar id={atividade.key} tarefa={atividade}/>
                             <ModalExcluir id={atividade.key} descricao={atividade.title}/>
                        </Col>
                    </Card.Body>
                </Card>
                 ))}
            </div>

        </Container>
    )
}

// vue-app/src/views/List.vue
<template>
  <div class="Conteiner">
    <div class="sairLogin" @click="sair">Sair</div>

    <div class="boxTop">
      <div class="TituloEmpresa">Sistema de controle de atividades</div>

      <b-navbar class="Navigation justify-content-between">
        <b-navbar-brand class="descricaoEmpresa"
          >Atividades cadastradas</b-navbar-brand
        >
        <b-form inline>
          <Cadastro />
        </b-form>
      </b-navbar>
    </div>

    <div class="boxContainer">
    
      <b-card class="mb-2 cardWidth"   
      v-for="(atividade, index) in tutorials"
      :key="index">
        <b-card-text class="FormTitle">  {{atividade.title}} </b-card-text>
        <b-card-text class="Formdescripton">  {{atividade.description}} </b-card-text>

        <b-card-text>
          <div class="FormDateTime">
            <div><i class="far fa-calendar"></i> {{atividade.date}}</div>
            <div><i class="far fa-clock"></i>{{atividade.time}}</div>
          </div>
        </b-card-text>

        <b-col cols="5" class="GroupBotaoStructure">
          <Excluir :idprops="atividade.key" :descricao="atividade.description" />
          <Atualizar :idprops="atividade.key" :tarefa="atividade" />
        </b-col>
      </b-card>
    </div>
  </div>
</template>

<script>

import { firebase } from '@firebase/app'
import DataService from "../services/service";

import Cadastro from "../components/ModalCadastro/cadastro.vue"
import Excluir from "../components/ModalExcluir/Excluir.vue"
import Atualizar from "../components/ModalAtualizar/atualizar.vue"

export default {
  name: "Lista",
  data() {
    return {
      id: 0,
      nome: "",
      cargo: "",
      tutorials: [],
      currentTutorial: null,
      currentIndex: -1,
      idprops: '',
      descricao: '',
      tarefa: '',

    };
  },
   components: {
   Cadastro,
   Excluir,
   Atualizar,
  },
  methods: {

      onDataChange(items) {
          let _tutorials = [];

          items.forEach((item) => {
            let key = item.key;
            let data = item.val();
            _tutorials.push({
              key: key,
              title: data.title,
              description: data.description,
              date: data.date,
              time:data.time,
            });
          });

          this.tutorials = _tutorials;
      },

      

     sair(){
        firebase.auth().signOut().then(() => {
            this.$router.push("/");
            // Sign-out successful.
          }).catch((error) => {
            // An error happened.
          });
    }

  },
  mounted() {
    DataService.getAll().on("value", this.onDataChange);
  },
  beforeDestroy() {
    DataService.getAll().off("value", this.onDataChange);
  }
};
</script>

<style  scoped>
.Conteiner {
  width: 100%;
  background: #f6f7f8;
  height: 100vh;
}

.boxTop {
  width: 100%;
  height: 200px;
  left: 0px;
  top: 0px;
  background: #0d3c3f;
}

.TituloEmpresa {
  font-family: "Righteous", cursive;
  font-size: 19px;
  line-height: 25px;
  display: flex;
  justify-content: center;
  text-transform: uppercase;
  color: #f8f8f8;
  padding: 20px;
}

.card-body {
  padding: 0 !important;
}

.descricaoEmpresa {
  font-family: "Righteous", cursive;
  font-size: 17px !important;
  line-height: 25px;
  text-transform: capitalize;
  color: #2fe95a !important;
}

.boxContainer {
  padding: 0 8rem;
  margin-top: -25px;
  display: grid;
  grid-template-columns: repeat(3, 20rem);
  grid-gap: 15px;
  justify-content: space-between;
}

.bodyTitle {
  font-weight: bold;
  font-size: 19px;
  color: #000000;
  font-family: "Roboto", sans-serif;
}

.GroupBotaoStructure {
  display: flex;
  justify-content: space-around;
  width: 115px;
  margin: auto;
  float: right;
}

.FormDateTime {
  width: 70%;
  display: flex;
  justify-content: space-between;
  color: grey;
  font-family: "Roboto", sans-serif;
  font-size: 1rem;
  font-weight: 400;
}

.FormTitle {
  font-weight: 400;
  color: #000000;
  font-family: "Roboto", sans-serif;
  font-size: 1.25rem !important;
}

.Formdescripton{
  color: grey;
  font-family: "Roboto", sans-serif;
  font-size: 1rem;
  font-weight: 400;
}

.sairLogin {
  position: fixed;
  margin-top: 18px;
  margin-left: 96%;
  text-align: right;
  color: rgb(248, 232, 0);
  cursor: pointer;
}

.cardWidth {
  width: 20rem;
  border: none;
  margin-bottom: 10px;
  font-weight: bold;
  font-size: 19px;
  color: #000000;
  font-family: "Roboto", sans-serif;
  padding: 1.5rem;
  font-size: 1.25rem !important;
}

h4,
.h4 {
  font-size: 1.25rem;
  margin-bottom: 0.75rem;
}
</style>>
